function gwt_mini_surfer(){var fb='',R=' top: -1000px;',ob='" for "gwt:onLoadErrorFn"',mb='" for "gwt:onPropertyErrorFn"',$='");',pb='#',Cb='.cache.js',rb='/',xb='//',Ab='2726E7D5AFF6C7446A33014710DB4EF6',Bb=':',gb='::',S='<html><head><\/head><body><\/body><\/html>',jb='=',qb='?',lb='Bad handler "',Y='Chrome',X='DOMContentLoaded',M='DUMMY',wb='base',ub='baseUrl',H='begin',N='body',G='bootstrap',tb='clear.cache.gif',ib='content',Eb='end',Z='eval("',I='gwt.codesvr.gwt_mini_surfer=',J='gwt.codesvr=',nb='gwt:onLoadErrorFn',kb='gwt:onPropertyErrorFn',hb='gwt:property',K='gwt_mini_surfer',zb='gwt_mini_surfer.devmode.js',vb='gwt_mini_surfer.nocache.js',eb='gwt_mini_surfer::',bb='head',O='iframe',sb='img',U='javascript',P='javascript:""',Db='loadExternalRefs',cb='meta',ab='moduleRequested',_='moduleStartup',db='name',Q='position:absolute; width:0; height:0; border:none; left: -1000px;',T='script',yb='selectingPermutation',L='startup',W='undefined',V='var $wnd = window.parent;';var o=window;var p=document;r(G,H);function q(){var a=o.location.search;return a.indexOf(I)!=-1||a.indexOf(J)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:K,sessionId:o.__gwtStatsSessionId,subSystem:L,evtGroup:a,millis:(new Date).getTime(),type:b})}}
gwt_mini_surfer.__sendStats=r;gwt_mini_surfer.__moduleName=K;gwt_mini_surfer.__errFn=null;gwt_mini_surfer.__moduleBase=M;gwt_mini_surfer.__softPermutationId=0;gwt_mini_surfer.__computePropValue=null;gwt_mini_surfer.__getPropMap=null;gwt_mini_surfer.__gwtInstallCode=function(){};gwt_mini_surfer.__gwtStartLoadingFragment=function(){return null};var s=function(){return false};var t=function(){return null};__propertyErrorFunction=null;var u=o.__gwt_activeModules=o.__gwt_activeModules||{};u[K]={moduleName:K};var v;function w(){y();return v}
function x(){y();return v.getElementsByTagName(N)[0]}
function y(){if(v){return}var a=p.createElement(O);a.src=P;a.id=K;a.style.cssText=Q+R;a.tabIndex=-1;p.body.appendChild(a);v=a.contentDocument;if(!v){v=a.contentWindow.document}v.open();v.write(S);v.close();var b=v.getElementsByTagName(N)[0];var c=v.createElement(T);c.language=U;var d=V;c.text=d;b.appendChild(c)}
function z(k){function l(a){function b(){if(typeof p.readyState==W){return typeof p.body!=W&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(X,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(X,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function m(c){function d(a,b){a.removeChild(b)}
var e=x();var f=w();var g;if(navigator.userAgent.indexOf(Y)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode(Z));for(var i=0;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(f.createTextNode(j.substring(1,j.length-1)))}h.appendChild(f.createTextNode($));g=f.createElement(T);g.language=U;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var i=0;i<c.length;i++){g=f.createElement(T);g.language=U;g.text=c[i];e.appendChild(g);d(e,g)}}}
gwt_mini_surfer.onScriptDownloaded=function(a){l(function(){m(a)})};r(_,ab);var n=p.createElement(T);n.src=k;p.getElementsByTagName(bb)[0].appendChild(n)}
gwt_mini_surfer.__startLoadingFragment=function(a){return C(a)};gwt_mini_surfer.__installRunAsyncCode=function(a){var b=x();var c=w().createElement(T);c.language=U;c.text=a;b.appendChild(c);b.removeChild(c)};function A(){var c={};var d;var e;var f=p.getElementsByTagName(cb);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(db),k;if(j){j=j.replace(eb,fb);if(j.indexOf(gb)>=0){continue}if(j==hb){k=i.getAttribute(ib);if(k){var l,m=k.indexOf(jb);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=fb}c[j]=l}}else if(j==kb){k=i.getAttribute(ib);if(k){try{d=eval(k)}catch(a){alert(lb+k+mb)}}}else if(j==nb){k=i.getAttribute(ib);if(k){try{e=eval(k)}catch(a){alert(lb+k+ob)}}}}}t=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;gwt_mini_surfer.__errFn=e}
function B(){function e(a){var b=a.lastIndexOf(pb);if(b==-1){b=a.length}var c=a.indexOf(qb);if(c==-1){c=a.length}var d=a.lastIndexOf(rb,Math.min(c,b));return d>=0?a.substring(0,d+1):fb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(sb);b.src=a+tb;a=e(b.src)}return a}
function g(){var a=t(ub);if(a!=null){return a}return fb}
function h(){var a=p.getElementsByTagName(T);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(vb)!=-1){return e(a[b].src)}}return fb}
function i(){var a=p.getElementsByTagName(wb);if(a.length>0){return a[a.length-1].href}return fb}
function j(){var a=p.location;return a.href==a.protocol+xb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==fb){k=h()}if(k==fb){k=i()}if(k==fb&&j()){k=e(p.location.href)}k=f(k);return k}
function C(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return gwt_mini_surfer.__moduleBase+a}
function D(){var f=[];var g;var h=[];var i=[];function j(a){var b=i[a](),c=h[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
s=function(a,b){return b in h[a]};gwt_mini_surfer.__getPropMap=function(){var a={};for(var b in h){a[b]=j(b)}return a};gwt_mini_surfer.__computePropValue=j;o.__gwt_activeModules[K].bindings=gwt_mini_surfer.__getPropMap;r(G,yb);if(q()){return C(zb)}var k;try{k=Ab;var l=k.indexOf(Bb);if(l!=-1){g=parseInt(k.substring(l+1),10);k=k.substring(0,l)}}catch(a){}gwt_mini_surfer.__softPermutationId=g;return C(k+Cb)}
function E(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}r(Db,H);r(Db,Eb)}
A();gwt_mini_surfer.__moduleBase=B();u[K].moduleBase=gwt_mini_surfer.__moduleBase;var F=D();E();r(G,Eb);z(F);return true}
gwt_mini_surfer.succeeded=gwt_mini_surfer();